# https://docs.docker.com/reference/compose-file/
name: zjusct-observability # COMPOSE_PROJECT_NAME variable

services:
# https://opentelemetry.io/docs/collector/installation/
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./config/otelcol/gateway.yaml:/etc/otelcol-contrib/config.yaml:ro
    # https://opentelemetry.io/docs/collector/configuration/#environment-variables
    environment:
      - OTEL_BEARER_TOKEN=${OTEL_BEARER_TOKEN}
    ports:
    # extension ports
      - 13133:13133   # health_check extension
      - 1777:1777     # pprof
      - 55679:55679   # zpages
    # receiver ports
    #  - 161:161       # SNMP (responses) receiver
    #  - 162:162       # SNMP (traps) receiver
      - 514:514/udp   # syslog receiver
    #  - 4317:4317     # OTLP gRPC receiver, conflict with host otel-collector
      - 4319:4318     # OTLP http receiver, conflict with host otel-collector
    restart: unless-stopped
    # cannot use any command in this image...
    # healthcheck:
    # if clickhouse is not ready, otel-collector will shutdown: cannot start pipelines
    depends_on:
      clickhouse:
        condition: service_healthy
        restart: true

# https://hub.docker.com/r/clickhouse/clickhouse-server/
  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - clickhouse:/var/lib/clickhouse
    # only for localhost
    ports:
      - 127.0.0.1:8123:8123 # HTTP interface
      - 127.0.0.1:9000:9000 # Native Client
    # https://github.com/plausible/analytics/discussions/4629#discussioncomment-10774222
    cap_add:
      - CAP_SYS_NICE
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SHOW DATABASES"]
      interval: 10s
      timeout: 3s
      retries: 3

# https://hub.docker.com/r/prom/prometheus/
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    # only for localhost
    ports:
      - 9090:9090
    restart: unless-stopped
    depends_on:
      - otel-collector # scrape from OpenTelemetry Collector
    healthcheck:
      # no curl command in the image
      test: ["CMD", "wget", "-q", "--spider", "http://prometheus:9090/-/healthy"]
      interval: 10s
      timeout: 3s
      retries: 3

# https://www.elastic.co/guide/en/elasticsearch/reference/8.15/docker.html
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch
#    volumes:
#      - elasticsearch:/usr/share/elasticsearch/data
#    ports:
#      - 127.0.0.1:9200:9200
#    healthcheck:
#      test:
#        [
#          "CMD-SHELL",
#          "curl http://localhost:9200",
#        ]
#      interval: 10s
#      timeout: 10s
#      retries: 120
#    command: -v

# https://hub.docker.com/r/grafana/grafana-enterprise/
  grafana:
    image: grafana/grafana-enterprise
    volumes:
      # https://grafana.com/docs/grafana/latest/administration/provisioning/
      - ./config/grafana:/etc/grafana
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - http_proxy=socks5://bridge.internal.zjusct.io:7891
      - https_proxy=socks5://bridge.internal.zjusct.io:7891
      - no_proxy=127.0.0.1,.cn,.zjusct.io
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on: # data source
      clickhouse:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://grafana:3000/"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  # https://stackoverflow.com/questions/74079078/what-is-the-meaning-of-the-type-o-device-flags-in-driver-opts-in-the-docker-comp
  clickhouse:
    driver: local
    driver_opts:
      type: none
      device: ./database/clickhouse
      o: bind
  prometheus:
    driver: local
    driver_opts:
      type: none
      device: ./database/prometheus
      o: bind
  grafana:
    driver: local
    driver_opts:
      type: none
      device: ./database/grafana
      o: bind
  elasticsearch:
    driver: local
    driver_opts:
      type: none
      device: ./database/elasticsearch
      o: bind
