{
 "title": "Defend Mirror",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "System Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Connections",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (system_network_connections{cloud_region=\"zjusct-falcon\", host_name=\"zjumirror\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_network_io_bytes_total{cloud_region=\"zjusct-falcon\", host_name=\"zjumirror\", direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "{{device}}-receive"
    },
    {
     "expr": "sum by(device) (rate(system_network_io_bytes_total{cloud_region=\"zjusct-falcon\", host_name=\"zjumirror\", direction=\"transmit\"}[$__rate_interval])) * -1",
     "legendFormat": "{{device}}-transmit"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device) (system_network_errors_total{cloud_region=\"zjusct-falcon\", host_name=\"zjumirror\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_network_packets_total{cloud_region=\"zjusct-falcon\", host_name=\"zjumirror\", direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "{{device}}-receive"
    },
    {
     "expr": "sum by(device) (rate(system_network_io_bytes_total{cloud_region=\"zjusct-falcon\", host_name=\"zjumirror\", direction=\"transmit\"}[$__rate_interval])) * -1",
     "legendFormat": "{{device}}-transmit"
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_network_dropped_total{cloud_region=\"zjusct-falcon\", host_name=\"zjumirror\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}