{
 "title": "Kubernetes Logs in ClickHouse",
 "description": "Simple dashboard for visualizing Kubernetes logs in ClickHouse",
 "time": { "from": "2022-10-26T15:13:45.834Z", "to": "2022-10-26T15:34:54.883Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "SELECT DISTINCT(host) as node FROM fluentbit.kube"
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "SELECT DISTINCT(pod_name) as node FROM fluentbit.kube "
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(host) FROM fluentbit.kube WHERE host != '' AND $__timeFilter(timestamp) AND pod_name IN (${pod_name}) AND host IN (${node})"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(pod_name) FROM fluentbit.kube WHERE host != '' AND $__timeFilter(timestamp) AND pod_name IN (${pod_name}) AND host IN (${node})"
    }
   ]
  },
  {
   "title": "Number of Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(log.kubernetes.docker_id) FROM fluentbit.kube WHERE $__timeFilter(timestamp) AND pod_name IN (${pod_name}) AND host IN (${node})"
    }
   ]
  },
  {
   "title": "Logs per Node",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT host as `Node`, count() as number FROM fluentbit.kube WHERE host != '' AND $__timeFilter(timestamp) AND pod_name IN (${pod_name}) AND host IN (${node})\tGROUP BY host ORDER BY number DESC"
    }
   ]
  },
  {
   "title": "Logs per Pod",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT pod_name as `Pods`, count() as number FROM fluentbit.kube WHERE host != '' AND $__timeFilter(timestamp) AND pod_name IN (${pod_name}) AND host IN (${node})\tGROUP BY pod_name ORDER BY number DESC"
    }
   ]
  },
  {
   "title": "Errors over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, level, count() FROM fluentbit.kube WHERE $__timeFilter(timestamp) AND pod_name IN (${pod_name}) AND host IN (${node}) GROUP BY multiIf(log.log ILIKE '%error%', 'error', log.log ILIKE '%warning%', 'warning', 'info') as level, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Logs over time per namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, namespace, count() as ` ` FROM fluentbit.kube WHERE $__timeFilter(timestamp) AND namespace != '' AND pod_name IN (${pod_name}) AND host IN (${node}) GROUP BY log.kubernetes.namespace_name as namespace, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Log messages",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT toDateTime(timestamp) as `log_time`,log.log as `Message`, host as `Node`, pod_name as `Pod` FROM fluentbit.kube WHERE $__timeFilter(timestamp) AND pod_name IN (${pod_name}) AND host IN (${node}) ORDER BY timestamp DESC"
    }
   ]
  }
 ]
}