{
 "title": "sFlow/Netflow Analytics",
 "description": "Flow Analytics with pmacct and ClickHouse",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Protocols In",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ip_proto, sum(bytes) FROM \"dankflows\".\"sflow\" WHERE ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) AND ( tag = 0 ) GROUP BY ip_proto"
    }
   ]
  },
  {
   "title": "Version Distribution",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(bytes) as IPv4 FROM \"dankflows\".\"sflow\" WHERE ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) AND ( family = 4 )"
    },
    {
     "rawSql": "SELECT sum(bytes) as IPv6 FROM \"dankflows\".\"sflow\" WHERE ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) AND ( family = 6 )"
    }
   ]
  },
  {
   "title": "Total Traffic Distribution By Router",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT label, sum(bytes) FROM \"dankflows\".\"sflow\" WHERE ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) GROUP BY label"
    }
   ]
  },
  {
   "title": "Traffic Distribution",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(bytes) as Inbound FROM \"dankflows\".\"sflow\" WHERE ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) AND ( tag = 0 )"
    },
    {
     "rawSql": "SELECT sum(bytes) as Outbound FROM \"dankflows\".\"sflow\" WHERE ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) AND ( tag = 1 )"
    }
   ]
  },
  {
   "title": "Protocols Out",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ip_proto, sum(bytes) FROM \"dankflows\".\"sflow\" WHERE ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) AND ( tag = 1 ) GROUP BY ip_proto"
    }
   ]
  },
  {
   "title": "Top Inbound ASNs",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT as_src_name, as_src, sum(bytes) FROM \"dankflows\".\"sflow\" WHERE ( tag = 0 ) AND ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) GROUP BY as_src_name, as_src"
    }
   ]
  },
  {
   "title": "Top Source IPs",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT ip_src, sum(bytes) FROM \"dankflows\".\"sflow\" WHERE ( tag = 1 ) AND ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) GROUP BY ip_src"
    }
   ]
  },
  {
   "title": "Top Destination IPs",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT ip_dst, sum(bytes) FROM \"dankflows\".\"sflow\" WHERE ( tag = 1 ) AND ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) GROUP BY ip_dst"
    }
   ]
  },
  {
   "title": "Top Outbound ASNs",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT as_dst, as_dst_name, sum(bytes) FROM \"dankflows\".\"sflow\" WHERE ( tag = 1 ) AND ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) GROUP BY as_dst, as_dst_name"
    }
   ]
  },
  {
   "title": "Top Inbound Flows Aggregate",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT ip_src, ip_dst, as_src_name, as_src, as_dst, sum(bytes) FROM \"dankflows\".\"sflow\" WHERE ( tag = 0 ) AND ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) GROUP BY ip_src, ip_dst, as_src_name, as_src, as_dst"
    }
   ]
  },
  {
   "title": "Top Outbound Flows Aggregate",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT ip_src, ip_dst, as_dst_name, as_src, as_dst, sum(bytes) FROM \"dankflows\".\"sflow\" WHERE ( tag = 1 ) AND ( stamp_inserted >= $__fromTime AND stamp_inserted <= $__toTime ) GROUP BY ip_src, ip_dst, as_dst_name, as_src, as_dst"
    }
   ]
  }
 ]
}