{
 "title": "NGINX请求日志分析看板 20241007 StarsL.cn",
 "description": "基于 ClickHouse + Vector 的NGINX请求日志分析看板。包括请求与耗时分析、异常请求分析、用户分析、地理位置分布图、指定接口分析、请求日志明细。https://grafana.com/orgs/starsliao/dashboards",
 "tags": [
  "StarsL.cn",
  "ClickHouse",
  "Vector",
  "Nginx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "项目", "query": "show tables" },
   {
    "name": "server_ip",
    "label": "NGINX",
    "query": "SELECT DISTINCT server_ip from $project"
   },
   {
    "name": "uri",
    "label": "指定接口分析",
    "query": "select path FROM ${project}\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\n\tgroup by path\n\torder by count() desc\nlimit 1000\n"
   }
  ]
 },
 "panels": [
  { "title": "请求与耗时分析", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT count()/10000 as \"今日总PV(万)\"\r\nFROM ${project}\r\n\tWHERE toDate(timestamp) = today() and server_ip in (${server_ip})"
    },
    {
     "rawSql": "\tSELECT COUNT(DISTINCT client_ip) AS \"今日总UV\"\r\n\tFROM ${project}\r\n\tWHERE toDate(timestamp) = today()  and server_ip in (${server_ip})\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time, count() / 15 AS \"今日最大QPS\"\r\n\tFROM ${project}\r\n\tWHERE toDate(timestamp) = today() and server_ip in (${server_ip})\r\n\tGROUP BY time"
    },
    {
     "rawSql": "SELECT toStartOfMinute(timestamp) AS time, sum(request_length) * 8 / 60 as \"今日最大请求量\"\r\n\tFROM ${project}\r\n\tWHERE toDate(timestamp) = today() and server_ip in (${server_ip}) \r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT toStartOfMinute(timestamp) AS time, sum(response_length) * 8 / 60 as \"今日最大返回量\"\r\n\tFROM ${project}\r\n\tWHERE toDate(timestamp) = today()  and server_ip in (${server_ip}) \r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 60 SECOND) AS time,countIf(status<400)/count() *100 as \"请求成功率\"\r\nFROM ${project} \r\nWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\ngroup by time\r\norder by time\r\n"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time, count()/15 AS \"实时QPS\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\n\tGROUP BY time\r\n  order by time"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,avg(responsetime) as \"实时响应时间\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE \r\n        WHEN status >= 200 AND status < 300 THEN '2XX'\r\n        WHEN status >= 300 AND status < 400 THEN '3XX'\r\n        WHEN status >= 400 AND status < 500 THEN '4XX'\r\n        WHEN status >= 500 AND status < 600 THEN '5XX'\r\n        ELSE 'Other'\r\n    END AS status_category,\r\n    COUNT(*) AS count\r\nFROM ${project}\r\nWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\nGROUP BY \r\n    status_category\r\norder BY\r\n    status_category"
    }
   ]
  },
  {
   "title": "每分钟HTTP200耗时分布",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\ntoStartOfMinute(timestamp) AS time,\r\n    CASE\r\n        WHEN responsetime >= 0 AND responsetime <= 0.01 THEN '0-10'\r\n        WHEN responsetime > 0.01 AND responsetime <= 0.025 THEN '0-25'\r\n        WHEN responsetime > 0.025 AND responsetime <= 0.05 THEN '1-50'\r\n        WHEN responsetime > 0.05 AND responsetime <= 0.1 THEN '2-100'\r\n        WHEN responsetime > 0.1 AND responsetime <= 0.25 THEN '3-250'\r\n        WHEN responsetime > 0.25 AND responsetime <= 0.5 THEN '4-500'\r\n        WHEN responsetime > 0.5 AND responsetime <= 1 THEN '5-1000'\r\n        WHEN responsetime > 1 AND responsetime <= 3 THEN '6-3000'\r\n        ELSE 'N-MAX'\r\n    END AS status_category,\r\n    COUNT() AS count\r\nFROM ${project}\r\nWHERE $__timeFilter(timestamp) and server_ip in (${server_ip}) and status=200\r\nGROUP BY \r\n    time,status_category\r\norder BY\r\n    time,status_category"
    }
   ]
  },
  {
   "title": "HTTP200响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,\r\n  quantileExact(0.99)(responsetime) as P99\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,\r\n  quantileExact(0.90)(responsetime) as P90\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,\r\n  quantileExact(0.50)(responsetime) as P50\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,\r\n  quantileExact(0.75)(responsetime) as P75\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,\r\n  quantileExact(0.95)(responsetime) as P95\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,avg(responsetime) as \"平均\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `top_path`, COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\",avg(response_length) as \"平均返回\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY `top_path`\r\n  order by COUNT() DESC\r\n"
    },
    {
     "rawSql": "\tSELECT\r\n\t  `top_path`,avg(responsetime) as \"HTTP200平均响应时间\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip}) and status = 200\r\n\tGROUP BY `top_path`"
    },
    {
     "rawSql": "SELECT `top_path`,\r\ncountIf(status >=400 and status < 500) as 4XX,\r\ncountIf(status>=500) as 5XX\r\nFROM ${project}\r\nWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\nGROUP BY \r\n    `top_path`"
    }
   ]
  },
  {
   "title": "各后端平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,upstreamhost,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\nGROUP BY time,upstreamhost\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "各后端每秒收到请求数(QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time, upstreamhost, count() / 15 AS avgqps\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\n\tGROUP BY time,upstreamhost\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time, count() / 15 AS avgqps\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "各后端每秒收到请求数占比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "每分钟非HTTP200的请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 60 SECOND) AS time,toString(status), count(status)  AS HTTP\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status != 200\r\n\tGROUP BY time,status\r\n  order by time"
    }
   ]
  },
  {
   "title": "请求方法占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  request_method, \r\n    COUNT()\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY request_method\r\n  order by COUNT() DESC"
    }
   ]
  },
  {
   "title": "各NGINX平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,server_ip,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\nGROUP BY time,server_ip\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "各NGINX每秒收到请求数(QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time, server_ip, count() / 15 AS avgqps\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\n\tGROUP BY time,server_ip\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time, count() / 15 AS avgqps\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "各NGINX每秒收到请求数占比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "HTTP 异常状态码(每分钟累计)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) as time,\r\n  count() as value,top_path,toString(status) as \"状态\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status >= 500\r\nGROUP BY time,status,top_path\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "异常请求分析",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求域名",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  `domain` as \"域名\", count() as PV,COUNT(DISTINCT client_ip) as UV,avg(responsetime) as \"平均响应时间\"\r\n\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY `domain`\r\n  order by COUNT() DESC"
      }
     ]
    },
    {
     "title": "请求耗时最慢TOP30（PV>100）",
     "type": "table",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  `path` as \"请求路径\", avg(responsetime) as \"平均响应时间\",COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\",avg(response_length) as \"平均返回量\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY `path`\r\n\tHAVING PV >100\r\n  order by avg(responsetime) DESC\r\n\tLIMIT 30;"
      }
     ]
    },
    {
     "title": "P90 NGINX处理耗时最慢 TOP30（PV>10）",
     "type": "table",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  `path` as \"请求路径\",quantileExact(0.90)(duration) as \"P90NG处理时间\",avg(response_length) as \"平均返回量\", avg(responsetime) as \"平均响应时间\",COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY `path`\r\n\tHAVING PV > 10\r\n  order by \"P90NG处理时间\" DESC\r\n\tLIMIT 30;"
      }
     ]
    },
    {
     "title": "请求来源TOP30",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  referer as Referer, \r\n    COUNT() as \"PV\", COUNT(DISTINCT client_ip) as \"UV\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY referer\r\n  order by COUNT() DESC\r\n\tLIMIT 30;"
      }
     ]
    },
    {
     "title": "各URI请求数TOP30",
     "type": "table",
     "gridPos": { "h": 9, "w": 9, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  `path` as \"请求路径\", COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\",avg(responsetime) as \"平均响应时间\",avg(response_length) as \"平均返回量\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY `path`\r\n  order by COUNT() DESC\r\n\tLIMIT 30;"
      }
     ]
    },
    {
     "title": "返回数据量TOP30",
     "type": "table",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  `path` as \"请求路径\",avg(response_length) as \"平均返回量\", avg(responsetime) as \"平均响应时间\",COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY `path`\r\n  order by avg(response_length) DESC\r\n\tLIMIT 30;"
      }
     ]
    },
    {
     "title": "TOP_Path大于500ms请求，占整体大于500ms请求的比例",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expression": "$A / $B", "type": "math" }
     ]
    },
    {
     "title": "TOP_Path每分钟耗时大于500ms的请求数",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT toStartOfMinute(timestamp) AS time, top_path\r\n\t, countIf(responsetime > 0.5) AS slow_requests\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) \r\nGROUP BY time, top_path\r\nHAVING slow_requests > 0\r\nORDER BY time"
      }
     ]
    },
    {
     "title": "TOP_Path每分钟返回数据量",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "SELECT toStartOfMinute(timestamp) AS time, top_path,sum(response_length) as \"返回量\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) \r\nGROUP BY time, top_path\r\nORDER BY time"
      }
     ]
    },
    {
     "title": "整体请求与返回量",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "rawSql": "SELECT toStartOfMinute(timestamp) AS time, sum(request_length) * 8 / 60 as \"每秒请求量\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) \r\nGROUP BY time\r\nORDER BY time"
      },
      {
       "rawSql": "SELECT toStartOfMinute(timestamp) AS time, sum(response_length) * 8 / 60 as \"每秒返回量\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) \r\nGROUP BY time\r\nORDER BY time"
      }
     ]
    },
    {
     "title": "每10分钟程序请求数",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 10 MINUTE) AS time, COUNT() as \"应用\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and (http_user_agent like '%Java%' OR http_user_agent like '%python%')\r\n\tGROUP BY time\r\n  order by time"
      },
      {
       "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 10 MINUTE) AS time, COUNT() as \"爬虫\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and (http_user_agent like '%spider%' OR http_user_agent like '%bot%')\r\n\tGROUP BY time\r\n  order by time"
      }
     ]
    },
    {
     "title": "各接口HTTP200平均响应时间",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,avg(responsetime) as \"平均\",top_path\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200\r\nGROUP BY time,top_path\r\nORDER BY time"
      }
     ]
    },
    {
     "title": "HTTP200 P90响应时间",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,quantileExact(0.90)(responsetime) as P90,top_path\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200\r\nGROUP BY time,top_path\r\nORDER BY time"
      }
     ]
    }
   ]
  },
  {
   "title": "用户分析",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "每分钟唯一IP",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 60 SECOND) AS time, COUNT(DISTINCT client_ip) AS \"唯一IP数\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\n\tGROUP BY time\r\n  order by time"
      }
     ]
    },
    {
     "title": "请求用户IP TOP30",
     "type": "table",
     "gridPos": { "h": 9, "w": 5, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  client_ip as \"用户IP\", \r\n    COUNT() AS PV, COUNT(DISTINCT `path`) as \"请求URL数\",sum(response_length) as \"接收数据量\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY client_ip\r\n  order by PV DESC\r\n\tLIMIT 30;"
      }
     ]
    },
    {
     "title": "请求省份占比",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 7, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  client_region, \r\n    COUNT() AS \"未解析\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY client_region"
      }
     ]
    },
    {
     "title": "请求城市占比",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  client_city, \r\n    COUNT() AS \"未解析\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY client_city"
      }
     ]
    },
    {
     "title": "请求操作系统占比",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  client_os_family, \r\n    COUNT() AS \"未解析\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY client_os_family\r\n"
      }
     ]
    },
    {
     "title": "请求浏览器TOP10",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 6, "x": 4, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  client_browser_family, \r\n    COUNT() AS \"未解析\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY client_browser_family\r\n  order by COUNT() DESC\r\n\tLIMIT 10;"
      }
     ]
    },
    {
     "title": "请求设备型号TOP10",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 7, "x": 10, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  client_device_model, \r\n    COUNT() AS \"总数\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip}) and client_device_model != ''\r\n\tGROUP BY client_device_model\r\n  order by COUNT() DESC\r\n\tLIMIT 10;"
      }
     ]
    },
    {
     "title": "请求设备品牌TOP10",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  client_device_brand, \r\n    COUNT() AS \"总数\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip}) and client_device_brand != ''\r\n\tGROUP BY client_device_brand\r\n  order by COUNT() DESC\r\n\tLIMIT 10;"
      }
     ]
    }
   ]
  },
  {
   "title": "地理位置分布图",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "最近1分钟各城市HTTP200平均响应时间与PV",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT client_region as \"省份\",client_city as \"城市\",avg(responsetime) as \"响应时间\",count() as \"PV\",COUNT(DISTINCT client_ip) as UV\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip}) and status=200\r\ngroup by client_region,client_city"
      }
     ]
    },
    {
     "title": "各城市QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 4 },
     "targets": [
      {
       "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time, client_city, count() / 15 AS avgqps\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip})\r\n\tGROUP BY time,client_city\r\n  order by time"
      }
     ]
    },
    {
     "title": "各城市HTTP200平均响应时间(QPS>1)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 11, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,avg(responsetime) as \"平均\",client_city\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200 \r\nGROUP BY time,client_city\r\nhaving count()/15 > 1\r\nORDER BY time"
      }
     ]
    },
    {
     "title": "HTTP200 P90响应时间(QPS>1)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,quantileExact(0.90)(responsetime) as P90,client_city\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200\r\nGROUP BY time,client_city\r\nhaving count()/15 > 1\r\nORDER BY time"
      }
     ]
    },
    {
     "title": "时段请求数分布",
     "type": "geomap",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT COUNT() AS PV, client_latitude as latitude ,client_longitude as longitude,client_city as \"城市\",client_region as \"省份\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip})\r\n\tGROUP BY client_latitude,client_longitude,client_city,client_region"
      }
     ]
    },
    {
     "title": "最近5分钟HTTP200平均响应延迟分布",
     "type": "geomap",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "\tSELECT avg(responsetime) as \"响应时间\", client_latitude as latitude ,client_longitude as longitude,client_city as \"城市\",client_region as \"省份\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip}) and status=200\r\n\tGROUP BY client_latitude,client_longitude,client_region,client_city"
      }
     ]
    }
   ]
  },
  {
   "title": "指定接口分析：$uri",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP200响应时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,\r\n  quantileExact(0.99)(responsetime) as P99\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200 and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
      },
      {
       "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,\r\n  quantileExact(0.90)(responsetime) as P90\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200 and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
      },
      {
       "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,\r\n  quantileExact(0.50)(responsetime) as P50\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200 and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
      },
      {
       "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,\r\n  quantileExact(0.75)(responsetime) as P75\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200 and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
      },
      {
       "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,\r\n  quantileExact(0.95)(responsetime) as P95\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200 and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
      },
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,avg(responsetime) as \"平均\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and status=200 and path='${uri}'\r\nGROUP BY time\r\nORDER BY time"
      }
     ]
    },
    {
     "title": "各后端平均响应时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,upstreamhost,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and path='${uri}'\r\nGROUP BY time,upstreamhost\r\nORDER BY time"
      },
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and path='${uri}'\r\nGROUP BY time\r\nORDER BY time"
      }
     ]
    },
    {
     "title": "各后端每秒收到请求数(QPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time, upstreamhost, count() / 15 AS avgqps\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and path='${uri}'\r\n\tGROUP BY time,upstreamhost\r\n  order by time"
      },
      {
       "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 15 SECOND) AS time, count() / 15 AS avgqps\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and path='${uri}'\r\n\tGROUP BY time\r\n  order by time"
      }
     ]
    },
    {
     "title": "HTTP状态码(每分钟累计)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) as time,\r\n  count() as value,toString(status) as \"状态\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(time) and server_ip in (${server_ip}) and path='${uri}'\r\nGROUP BY time,status\r\nORDER BY time\r\n"
      }
     ]
    },
    {
     "title": "【$uri】请求明细TOP100（本页所有图表均关联该接口）",
     "type": "table",
     "gridPos": { "h": 19, "w": 20, "x": 4, "y": 13 },
     "targets": [
      {
       "rawSql": "\r\nSELECT timestamp, status, request_method, domain,query,server_ip,upstreamhost,responsetime,upstreamtime,request_length,response_length,client_ip,client_city\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip}) and status=200 and path = '${uri}'\r\n\r\norder by timestamp desc\r\nlimit 100\r\n"
      }
     ]
    },
    {
     "title": "请求用户IP TOP30",
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  client_ip as \"用户IP\", \r\n    COUNT() AS PV, avg(responsetime) as \"平均响应时间\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip}) and path='${uri}'\r\n\tGROUP BY client_ip\r\n  order by PV DESC\r\n\tLIMIT 30;"
      }
     ]
    }
   ]
  },
  {
   "title": "请求日志明细",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求明细（最近500条）",
     "type": "table",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "\r\nSELECT timestamp, status, request_method, domain,path,query,server_ip,upstreamhost,responsetime,upstreamtime,request_length,response_length,client_ip,client_city\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and server_ip in (${server_ip}) and status=200\r\n\r\norder by timestamp desc\r\nlimit 500\r\n"
      }
     ]
    }
   ]
  }
 ]
}