{
 "title": "ZJU Mirror",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Host CPU Load",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_cpu_load_average_5m{host_name=\"zjumirror\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Memory Percent",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_percent_ratio{host_name=\"zjumirror\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(direction) (rate(system_network_io_bytes_total{host_name=\"zjumirror\", device=\"ens160\"}[$__rate_interval]))",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "Dockers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "jobs-rsync I/O rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{container_hostname=\"zjumirror\", container_name=~\"job-rsync.+\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "jobs-rsync CPU %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{container_hostname=\"zjumirror\", container_name=~\"job-rsync.+\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "jobs-ftpsync I/O rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{container_hostname=\"zjumirror\", container_name=~\"job-ftpsync.+\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "jobs-ftpsync",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(container_name) (container_cpu_utilization_ratio{container_hostname=\"zjumirror\", container_name=~\"job-ftpsync.+\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "other docker",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(container_name) (container_cpu_utilization_ratio{container_hostname=\"zjumirror\", container_name!~\"job.+\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}