{
 "title": "ZJUSCT Cluster",
 "tags": [
  "clickhouse",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cloud_region", "label": "Cloud Region", "query": { "query": "label_values(cloud_region)" } },
   {
    "name": "host_name",
    "label": "Host Name",
    "query": {
     "query": "label_values({cloud_region=\"$cloud_region\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(__name__) (system_cpu_load_average_5m{cloud_region=\"$cloud_region\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 6, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "sum by(host_name) (system_memory_usage_bytes{cloud_region=\"$cloud_region\", state=\"used\"}) / sum by(host_name) (system_memory_usage_bytes{cloud_region=\"$cloud_region\"})",
     "legendFormat": "{{host.name}}"
    }
   ]
  },
  {
   "title": "Cluster Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n  Timestamp as \"timestamp\", \n  Body as \"body\", \n  SeverityText as \"level\", \n  LogAttributes as \"labels\", \n  ResourceAttributes as \"resource\", \n  TraceId as \"traceID\" \nFROM \"default\".\"otel_logs\" \nWHERE \n  ( timestamp >= $__fromTime AND timestamp <= $__toTime ) \n  AND ( '$cloud_region' == ' ' OR ResourceAttributes['cloud.region'] = '$cloud_region' ) \n  AND ( '$host_name' == ' ' OR ResourceAttributes['host.name'] = '$host_name' )\nORDER BY timestamp \nDESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Cluster Load",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg by(host_name) (system_cpu_load_average_5m{cloud_region=\"$cloud_region\"})",
     "legendFormat": "{{host.name}}"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Docker CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_cpu_utilization_ratio{host_name=\"Root\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Docker Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_file_bytes{host_name=\"Root\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "PDU Energy",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_energy_kWh{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_power_watt{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Energy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_current_ampere{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Power Factor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_power_factor_ratio{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}