{
 "title": "OpenTelemetry Collector Host Metrics Receiver",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cloud_region", "label": "Cloud Region", "query": { "query": "label_values(cloud_region)" } },
   {
    "name": "host_name",
    "label": "Host Name",
    "query": {
     "query": "label_values({cloud_region=\"$cloud_region\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(host_cpu_model_name) (system_cpu_frequency_hertz{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frequency per Core",
   "type": "heatmap",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(cpu) (system_cpu_frequency_hertz{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(host_name) (system_cpu_utilization_ratio{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (rate(system_cpu_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "I/O Time Delta",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "topk(10, sum by(device) (delta(system_disk_io_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_disk_io_bytes_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_disk_operations_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Operation Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_disk_operation_time_seconds_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Load Avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (system_cpu_load_average_1m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "1m"
    },
    {
     "expr": "sum by(host_name) (system_cpu_load_average_5m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "5m"
    },
    {
     "expr": "sum by(host_name) (system_cpu_load_average_15m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (system_cpu_load_average_1m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "1m"
    },
    {
     "expr": "sum by(host_name) (system_cpu_load_average_5m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "5m"
    },
    {
     "expr": "sum by(host_name) (system_cpu_load_average_15m{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "15m"
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(mountpoint) (system_filesystem_inodes_usage{cloud_region=\"$cloud_region\", host_name=\"$host_name\", state=\"used\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(mountpoint) (system_filesystem_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\", state=\"used\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(mountpoint) (system_filesystem_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\", state=\"free\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (system_memory_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (system_memory_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Connections",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(state) (system_network_connections{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_network_io_bytes_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "{{device}}-receive"
    },
    {
     "expr": "sum by(device) (rate(system_network_io_bytes_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"transmit\"}[$__rate_interval])) * -1",
     "legendFormat": "{{device}}-transmit"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_network_errors_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_network_packets_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "{{device}}-receive"
    },
    {
     "expr": "sum by(device) (rate(system_network_packets_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\", direction=\"transmit\"}[$__rate_interval])) * -1",
     "legendFormat": "{{device}}-transmit"
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device) (rate(system_network_dropped_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Paging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (system_paging_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (rate(system_paging_faults_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(direction, type) (rate(system_paging_operations_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(status) (system_processes_count{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Created Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host_name) (rate(system_processes_created_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Threads",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum by(process_executable_name) (process_threads{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(100, sum by(process_executable_name) (process_cpu_utilization_ratio{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(process_executable_name) (process_memory_usage_bytes{cloud_region=\"$cloud_region\", host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(process_executable_name) (rate(process_disk_io_bytes_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(process_executable_name) (rate(process_disk_operations_total{cloud_region=\"$cloud_region\", host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}