{
 "title": "OpenTelemetry Collector Container Stats Receiver",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cloud_region", "label": "Cloud Region", "query": { "query": "label_values(cloud_region)" } },
   {
    "name": "host_name",
    "label": "Host Name",
    "query": {
     "query": "label_values({cloud_region=\"$cloud_region\"},host_name)"
    }
   },
   {
    "name": "container_runtime",
    "label": "Container Runtime",
    "query": {
     "query": "label_values({cloud_region=\"$cloud_region\", host_name=\"$host_name\"},container_runtime)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$container_runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "container_runtime" },
  {
   "title": "CPU Utilization",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_uptime_seconds{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"$container_runtime\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (container_cpu_utilization_ratio{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"$container_runtime\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (container_memory_percent_ratio{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"$container_runtime\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (container_memory_file_bytes{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"$container_runtime\"})",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"$container_runtime\", operation=\"write\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"$container_runtime\", operation=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Block I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"$container_runtime\", operation=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{container_name}}-read"
    },
    {
     "expr": "sum by(container_name) (rate(container_blockio_io_service_bytes_recursive_total{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"$container_runtime\", operation=\"write\"}[$__rate_interval])) * -1",
     "legendFormat": "{{container_name}}-write"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_cpu_utilization_ratio{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"$container_runtime\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_file_bytes{host_name=\"$host_name\", cloud_region=\"$cloud_region\", container_runtime=\"$container_runtime\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}