{
 "title": "SNMP PDU Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PDU Power Factor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_power_factor_ratio{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Energy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_current_ampere{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_power_watt{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Energy",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device_id) (pdu_energy_kWh{pdu_port_type=\"input\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}