{
 "title": "ZJUSCT Cluster",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Cluster Load",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(__name__) (otel_system_cpu_load_average_5m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Load",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(host_name) (otel_system_cpu_load_average_5m)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Root Load",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(otel_system_cpu_load_average_5m{host_name=\"Root\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (otel_system_memory_usage_bytes{host_name=\"Root\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Docker CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_name) (otel_container_cpu_utilization_ratio{host_name=\"Root\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Docker Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(container_name) (otel_container_memory_file_bytes{host_name=\"Root\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}